apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: entity-recognition
spec:
  template:
    metadata:
      labels:
        app: entity-recognition
    spec:
      containers:
      - name: entity-recognition
        image: igorbonadio/entity-recognition:1.0.0
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: entity-recognition
spec:
  selector:
    app: entity-recognition
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer